ninjadev/nin

- nin/dasBoot/CameraController.js
- nin/dasBoot/PathController.js
- nin/dasBoot/bootstrap.js
- nin/example-project/res/camerapaths.json
- nin/example-project/src/BlankLayer.js
- nin/example-project/src/MountainLayer.js
- nin/frontend/app/scripts/services/camera.js
This changes the semantics of the connection between a camerapath and a layer slightly.
The old format matched camerapaths in camerapaths.json with corresponding layers in layers.json by their index in the list. This made it difficult to actually keep a camerapath connected to the proper
layer.
A full rework of the system (diffent camerapaths in different files or something similar) might be best, but that's too much work to be completed before solskogen 2015.
The old format meant that a camerapath was linked to an instance of the layer, i.e. two different instances of the layer could (and would) have different camerapaths. With the new system, the camerapath is instead linked to the 'type' of the layer, as `camerapaths.json` is no longer a list, but a dictionary where the layer type is …
> Refactor cam control

- nin/backend/socket.js
The layers.json file didn't have the correct newline on the end of the
file when it was edited from nin.
> Add newline to layers.json file when writing

- nin/backend/package.json
Newer versions break png.html-compression.
> Lock crc dependency version to 2.0.0

- nin/dasBoot/interpolations.js
They interpreted easeIn(a, b, t) as easeIn(a, a+b, t)
or backwards...
> Fix easeIn and easeOut

- nin/dasBoot/PathController.js
They mostly just returned NaN, it turns out
> Fix 1D paths in path controller

- nin/backend/package.json
- nin/backend/serve.js
`nin run` should now work as expected on Windows. I haven't tested it on Mac and Linux.
> Normalize paths and use node modules for find and cat operations

- nin/frontend/app/styles/main.css
I think I recall testing display: block before, but I don't remember why I decided not to push it.
Anyway, it seems to fix issues I see with layers ending up in the wrong spot in the layers panel
**Bad:**
**Good:**
> Remove dbl scroll

- nin/dasBoot/Loader.js
- nin/frontend/app/scripts/controllers/main.js
Now you should, as always, never call Loader.start.
> Improve Loader

- nin/backend/nin
- nin/backend/serve.js
- nin/frontend/Gruntfile.js
This lets users supply a custom frontend if they want, which is useful
for developing the frontend with e.g. grunt.
> Add option to run nin headlessly

- README.md
nin.sexy isn't up right now, so the link is removed in this commit.
> Remove nin link in Readme

- Makefile
- README.md
- nin/Makefile
It makes more sense to have the backend+frontend makefile here, not too far away from the backend and frontend folders themselves.
> Move makefile inside nin folder

- nin/backend/socket.js
- nin/frontend/app/scripts/controllers/main.js
Layers can declare dependencies on shaders in layers.json.
They will then be automatically reloaded when a shader they depend on
changes.
This basically means you get shadertoy-like behavior when using nin with
a text editor on your computer!
> Reload layers when shaders are updated

- nin/backend/package.json
- nin/backend/serve.js
- nin/backend/shadergen.js
- nin/backend/socket.js
- nin/backend/watch.js
- nin/frontend/app/scripts/controllers/main.js
Now there's only one file watcher, even though you may have multiple
frontends running.
Shaders are now compiled only once per file change, and the initial
compile is also moved to nin boot, instead of on browser socket
connection.
This should make for less unnecessary recompiling and file watching,
less network traffic, and less spammy terminal output.
> Refactor file watcher

- nin/frontend/app/scripts/controllers/main.js
We don't really need the keyboard shortcuts overlay anymore, so this replaces that menu item with something a little bit more useful
> Add link to online wiki in help menu

- nin/backend/render.js
It turns out that itsoffset is not interpreted in the same way by all
codecs/players etc.
Without really understanding everything about avconv, testing with
multiple renders and watching videos played back in slow motion proved
that removing the negative itsoffset yielded the best synced video &
audio.
> Remove itsoffset from avconv parameters w/@sigvef

- nin/backend/serve.js
Previously, dasBoot script files were guaranteed to be concat in the
following order: 1) all files from dasBoot/lib in alphabetical order, 2)
all other files from dasBoot in alphabetical order. This was useful
because it let us control dependencies between dasBoot components. This
ordering disappeared in 74bb5aabb30d6892a4c1734e03819ff502dfcac0. This
commit reintroduces this ordering.
> Repair dasBoot concat order

- nin/dasBoot/Loader.js
The loadAjax signature was changed from loadAjax(path, callback) to
loadAjax(path, options, callback), and to make things backwards
compatible, the options parameter in the middle is optional, letting old
calls still work. However, there was a bug in the implementation of this
backwards compatibility. This bug is fixed in this commit.
> Fix loadAjax bug where old-format calls would die

- nin/dasBoot/LayerManager.js
- nin/dasBoot/PathController.js
- nin/frontend/app/scripts/controllers/main.js
- nin/frontend/app/scripts/services/demo.js
Nintage now has support to on-demand generate camerapath- and any other path visualizations.
This is pretty cool to check out where the camera actually goes!
> Add pathVisualization to dasBoot, pathController

- nin/backend/projectSettings.js
- nin/backend/render.js
- nin/dasBoot/music.js
- nin/frontend/app/scripts/directives/waveform.js
Previously, you had to have a song called music.mp3 in res, now you can
choose yourself, allowing for easy switching if needed.
> Make demo music path user configurable through nin.json

- nin/dasBoot/Loader.js
- nin/dasBoot/music.js
Now, Loader.loadAjax-calls that expect arraybuffer response types must
accept a signalling callback to *their* callback to let the loader know
that the item callback is done preparing whatever it is they need to
prepare. Phew!
This fixes #176.
> Repair compile for arraybuffer-based music

- nin/frontend/app/styles/main.css
This box (and the BEAN box) now passes through clicks.
> Pass pointer events through frame, BEAN counter

- nin/dasBoot/Loader.js
Since 0e72dda2ec640ab1ab0b66559d553543e627c7f9, loadAjax calls with
response type arraybuffer, expect to call registerAsLoaded explicitly
after receiving their response. However, this was only implemented
properly for compiled loads, and not regular ajax loads.
> Pass callback function to arraybuffer loaders

- nin/backend/compile.js
- nin/backend/serve.js
- nin/backend/watch.js
lib/ dependencies in src are now properly loaded when using nin. Initial
script loads are now done alphabetically to get a predictable execution
order. Conveniently, lib is before src in the alphabet, so lib files
are loaded first. For compilation, project lib scripts are now added to
closure compiler directly instead of using the old (and broken) manual
concatenation approach.
> Add lib/ folder support to nin projects

- nin/dasBoot/LayerManager.js
LayerManager calls each layer's render method from its render method,
but previously failed if a layer didn't implement it.
> Check for presence of layer's render method

- nin/backend/utils.js
Some commands (nin compile, for instance) depend on the projectPath
variable to parse file names.
There was an issue where filenames in FILES[] were written as
'es/filename.ext' (missing the r) when projectPath ended in a trailing
slash.
> Normalize project root path

- nin/frontend/app/scripts/controllers/main.js
- nin/frontend/app/styles/common.less
- nin/frontend/app/styles/themes/dark.less
- nin/frontend/app/styles/themes/light.less
- nin/frontend/app/views/main.html
This lets the user if the frontend has disconnected from the backend for
some reason. This might happen e.g. if the backend crashes.
> Add disconnected message banner

- nin/backend/compress.js
This fixes #216 
Since version 3.0.0, crc32 requires input values to be Buffer instances.
> Ensure crc input values are Buffer instances

- nin/dasBoot/LayerManager.js
This is useful for e.g. accessing demo.renderer in layers.
> Inject demo instance to layers

- README.md
- nin/frontend/app/scripts/controllers/main.js
- nin/frontend/app/scripts/directives/keybinding.js
* stiaje, sigveseb and I have at some point accidentally pressed `shift + R` in nin. That is ever so slightly annoying, because it brings nin to its knee and starts filling up the disk while it is not obvious what is happening.
* Since rendering frames is not something we do often, and we have a menu now, it does not need a keyboard shortcut anymore
> Remove keyboard shortcut for rendering frames (shift + R)

- nin/frontend/app/scripts/controllers/bottom.js
- nin/frontend/app/views/bottom-panel.html
The music timeline now always fills the width of the screen.
This fixes #258.
This fixes #226.
> Disable horizontal zooming

- nin/frontend/app/styles/common.less
- nin/frontend/app/views/bottom-panel.html
Now it does not leave a glow trail when the demo is not playing. Also,
the effect has been reduced a bit to match the fact that the music
timeline can no longer be zoomed.
> Tweak playback glow line style

- nin/backend/.eslintrc.js
- nin/backend/compile.js
- nin/backend/generate/generate.js
- nin/backend/socket.js
- package.json
The lint command in package.json is updated so that the eslint runs with
backend as cwd. This ensures that it loads the correct .eslintignore
Templates in the generate folder are ignored since they're not strictly
part of the backend, but templates for user projects.
Also, one lint error remains, but it's there because the feature is
still broken so I figured it serves as a nice reminder to fix the
feature.
> Lint remaining backend files

- nin/frontend/app/scripts/controllers/main.js
Layers -> Generate node in the frontend seems to crash while it didn't
before. If i remember correctly, this is one of the reasons createNode
was inside the try-catch to begin with, and is therefore moved back.
> Potentially fix race-condition regression with layer generation

- README.md
- nin/backend/blank-project/.gitignore
- nin/backend/generate/generate.js
- nin/backend/init.js
- nin/backend/nin
- nin/backend/projectSettings.js
Modelled after rust's cargo, nin init now takes a required directory
argument, avoiding accidentally initializing nin projects in your
current directory (as many zip-users may be familiar with).
Additionally, nin projects now come with git initialized as well as a
bundled .gitignore tailored for our project format.
This will reduce onboarding friction for new users, as well as
profilerating the spread of git and allowing for easier sharing on
github.
> Make nin init take directory, init as git repository

- nin/backend/nin
Before, the CLI would just silently exit if you tried running it with an
invalid command, e.g. `nin yolo`. Now, the CLI prints the default help
message instead.
before:
after:
> Show help message for invalid commands

- nin/backend/compile.js
- package.json
- yarn.lock
The Google Closure Compiler now has an official js port, so we can use
that instead. The upside for us is that we no longer have a Java
dependency, and we can have a cleaner-looking compile implementation
that doesn't rely on external executables.
Of course, compilation is currently broken in master since the switch to
nodes instead of layers, so compiling anything on this commit won't
technically work. However, this should "totally work" when we fix the
other stuff.
> Replace closure compiler with js implementation

- nin/backend/nin
- nin/backend/serve.js
Headlessly was ran when the frontend was gulp-based,
and you wanted to dev on it.
Now that everything's webpack, the command's no longer needded.
> Remove dead code nin command

- nin/backend/nin
Previously, generic help text would be displayed when running a command
with optional arguments. Now, the help text is correctly only displayed
when nin is run with no commands at all, or when passed -h or --help.
> Fix bug in cli help display

- nin/dasBoot/PathController.js
For circle animations, clamp internal time value to the end instead of
jumping back to the start.
> Stay at end of camerapath instead of skip to start

- nin/frontend/app/scripts/directives/editor/GraphEditor.js
- nin/frontend/app/scripts/directives/editor/GraphEditorInputOutput.js
- nin/frontend/app/scripts/directives/editor/GraphEditorNode.js
- nin/frontend/app/styles/common.less
This makes the root view a bit more useful, showing connection names at the new default zoom level.
> Graph improvements

- nin/frontend/app/scripts/directives/menubar.js
We swapped the j and k shortcuts some time ago, but we forgot to also
swap shift-j and shift-k. Now, these are swapped.
> Swap derivative j k shortcuts

- nin/frontend/app/scripts/directives/menubar.js
'f' was colliding with the flyaround controls up / down elevation buttons (bound to r and f).
Backwards compatibility can be attained by creating a .ninrc in your
root folder with the following contents:
```
[keybinds]
toggleFullscreen=f
```
> Rebind fullscreen to enter from f

- nin/dasBoot/THREENode.js
- nin/frontend/app/scripts/controllers/main.js
The CameraNode doesn't exist anymore, and thus the live-reloading needed
a small update.
> Repair live-reloading of camera paths

- nin/backend/utils.js
When nin is installed from npm, git is not available. We just let the
git commands fail silently then.
This fixes #344
> Don't crash if git commands fail in nin

- nin/dasBoot/NodeManager.js
- nin/dasBoot/ShaderNode.js
- nin/frontend/app/scripts/controllers/main.js
Any node that specifies the name of a shader in options.shader will be
reloaded when that file changes.
Support for live-reloading based on multiple shaders comes in The™
Future™.
> Implement shader live reloading

- nin/dasBoot/ShaderNode.js
This needs to be done so that we can have separate uniforms per node
instantiation.
> Clone ShaderMaterial in ShaderNode

- Makefile
Turns out yarn's publish command isn't equivalent to npm's and npm's is nicer for our use-case
> Switch yarn to npm

- nin/frontend/app/scripts/directives/editor/GraphEditor.js
- nin/frontend/app/scripts/directives/editor/GraphEditorInputOutput.js
Click a node input or output to inspect it. If the item holds a texture
value, it will be rendered to the screen for inspection! In the future,
we can add inspection for other types as well, and for other items like
nodes.
> Add item previews

- nin/frontend/app/scripts/directives/editor/GraphEditorInputOutput.js
Since we can (soon ?) inspect items now, we don't need as much info in
the preview. The foreignObject tables were slowing things down when
zoomed in too much anyway!
> Replace graph preview system with basic type info

- nin/dasBoot/PathController.js
Now allows animating the center point as a 3D path, and the radius as a
two-step animation.
Also the default value for length is now a much more sane 1 instead of
0.
> Add features to cameracontroller circle path

- nin/dasBoot/PathController.js
PathController allows multiple property names to be used for the same
value, but if the value was set to 0, the fallback chain would collapse
because 0 is a falsy value.
> Don't fallback on falsy values in PathController

- nin/backend/compile.js
- nin/backend/compress.js
- nin/dasBoot/bootstrap.js
This makes BEATBEAN properly available in Node constructors in compiled
demos.
> Fix BEATBEAN ordering when compiling

- nin/backend/compile.js
OptiPNG crashes when trying to optimize multiple png's after one
another.
> Use new instance of optipng per file

- nin/backend/generate/TemplateShaderNode.js
- nin/backend/generate/generate.js
This means live-reload for shaders will be enabled by default.
This fixes #373.
> Update ShaderNode generation to use graph.json

- nin/backend/generate/generate.js
process.stderr.write only accepts one argument
> Fix printing of error message for generate command

- nin/backend/compile.js
- nin/backend/nin
This will make compiling the demo significantly faster if you have large
PNG's that are already fully optimized on disk.
> Add option for disabling optipng

- nin/backend/blank-project/res/graph.json
The initial graph.json had a typo,
which now has been corrected.
Fixes #389
> Fix broken project scaffold

- nin/backend/blank-project/res/graph.json
- nin/backend/blank-project/src/SceneSwitcherNode.js
Based on our experiences from revision, i've added a minimal SceneSwitcherNode to help new projects get started.
Additionally, it counts as documentation, giving an example on how to switch between multiple nodes based on the current BEAN.
> Add default SceneSwitcherNode to ease new project startup

- nin/dasBoot/bootstrap.js
- nin/frontend/app/scripts/utils/render.js
- nin/frontend/app/styles/common.less
This fixes two issues:
1. When the demo reaches the end during playback, it sometimes ended on a decimal-numbered frame. Frame numbers will with this fix always be integers.
2. When rendering a demo to images, the rendering never stopped, even after the end of the song. This is now resolved.
> Stop demo properly when it reaches end

- nin/backend/compile.js
- nin/backend/fontgen.js
- nin/backend/serve.js
- nin/frontend/app/index.html
Fonts can now be added to the res/ folder, and they will be
automagically be made available as a `@font-face` with the same name as
the font file (without suffix). As an example: `res/myfont.otf` will be
available for a 2D canvas as `ctx.font = '10pt myfont';`. Only .otf is
supported for now.
Before this commit, the typical way of adding fonts was to manually
convert otf to base64 offline, load that with Loader.loadAjax, and take
care to create a style tag with the font definition somewhere in the
demo.
Some font loaded in some demo:
Fonts being skipped when assimilating res:
> Add better font support

- nin/frontend/app/scripts/components/menubar.js
- nin/frontend/app/scripts/utils/ninrc.js
Keybindings might not be available before fetch completes, but should be
close to instantaneous.
> Fetch ninrc asynchronously with fetch

- nin/frontend/app/scripts/components/main.js
Turns out we have kept around a volume parameter for a while without
ever having a possibility to set the volume to anything other than 1 or
0. I take this as a hint that this functionality is not needed and
simplified the muting a bit in the process.
> Fix loading of muted state from local storage

- nin/frontend/app/scripts/components/editor/GraphEditor.js
- nin/frontend/app/scripts/components/editor/GraphEditorInputOutput.js
Store the inspection state on the react component instead of on the node
instance to make it persist over the reload of node instances.
> Maintain inspection state over node reloads

- nin/frontend/app/scripts/components/editor/FlyaroundController.js
- nin/frontend/app/scripts/components/editor/GraphEditorNode.js
This fixes an issue where flyaround controls stops working when a node
is reloaded.
> Reload flycontrols when a node is updated

- nin/frontend/app/scripts/components/waveform.js
Without this, the canvas would not be correctly sized on retina screens.
> Specify displayed width of waveform canvas

- nin/dasBoot/THREENode.js
4545fcdc1808618723a4f5cd8a228b5c0b121ab7 broke nodes that did not have
an output property specified at all, and that relied on NIN.Node to
provide the whole output setup for them. This made ninjadev/re stop
working, so here's a fix for that.
> Make sure nodes always have an output property

- nin/backend/blank-project/res/graph.json
This breaks auto-reload in newly generated projects.
> Remove double node connection in default graph

- nin/backend/serve.js
- nin/frontend/Makefile
- nin/frontend/app/dark.js
- nin/frontend/app/dark.ts
- nin/frontend/app/light.js
- nin/frontend/app/light.ts
- nin/frontend/app/scripts/app.js
- nin/frontend/app/scripts/app.tsx
- nin/frontend/app/scripts/components/main.tsx
- nin/frontend/app/scripts/socket.ts
- nin/frontend/package.json
- nin/frontend/tsconfig.json
- nin/frontend/webpack.config.js
- nin/frontend/yarn.lock
This commit introduces Typescript to our Webpack 2.0 flow.
Advantages include help from the compiler in weeding out logic errors in
components/main.js (i've simplified the websocket event type already),
and better compile time verification of our code.
I've not added ts to the backend (yet), as i couldn't figure out a
satisfactory build system just yet (just putting the compiled .js in
backend/dist could probably work).
I've yet to find a proper way of sharing files across the two projects,
as i initallly wanted to share the WSEvent type, so that i'd be
guaranteed the data sent over the socket matched the structure of the
one received.
> Start gradual typing of frontend

- nin/backend/compile.js
- nin/backend/fontgen.js
otf files have no compression while woff and woff2 provide much smaller
font files. The one example I tested on (the font vcr from `re`) was
half the filesize of the corresponding otf file, and reduced the size of
the .png-compiled demo by almost 2 kB (that's almost half a 4k demo!).
Woff2 also has basically as good browser support as otf, only lacking
internet explorer (but edge works!), and Safari for those not running
the latest macOS/iOS. Before we release another prod, I don't think that
will be an issue.
> Switch font loader to use woff2 instead of otf

- nin/frontend/app/scripts/components/editor/GraphEditor.jsx
During react unique key logspam debugging i ended up porting this file to JSX.
The source was found to be somewhere else, but if we want this to be JSX instead now, we can!
Should be functional now.
Depends on https://github.com/ninjadev/nin/pull/440
> Translate parts of GraphEditor.js to JSX

- nin/frontend/app/scripts/components/demoplayer.js
- nin/frontend/app/scripts/components/main.tsx
- nin/frontend/app/scripts/demo.js
Some of the error message code has been broken for a bit. 1) Error
messages from a web socket load have not been clearing themselves
automatically when the error has been fixed, and 2) error messages from
the looper have not been displayed at all. This commit fixes both of
these regressions.
Auto-clearing:
looper errors:
> Repair error messages

- package.json
- yarn.lock
Google Closure Compiler has started work on outputting es2015 instead of
only support ES5 output! It is still experimental, and lots of
optimization passes are currently skipped when using it, but this means
they will probably soon support it more and more. They also now default
to running all ES6 code in strict mode.
https://github.com/google/closure-compiler/wiki/Releases
> Update to latest Closure compiler

- nin/dasBoot/NodeManager.js
- nin/frontend/app/scripts/components/editor/GraphEditorInputOutput.js
A single output can have more than one destination, so we should either
store all or none of them on an output. This commit does the latter.
Practical consequences of this is that we now support proper
live-reloading of nodes that have multiple paths to the root node.
> Remove destination on Outputs

- Makefile
- README.md
- nin/frontend/Makefile
- nin/frontend/package.json
- package.json
This way systems without make can run `yarn start` in the root folder instead of having to install make for windows from sourceforge.
> Make makefile forward commands to package.json

- nin/dasBoot/NodeManager.js
- nin/dasBoot/bootstrap.js
- nin/dasBoot/node.js
This is useful for enabling and disabling inputs before update and
render is called. The practical impact of this is that the oft-used
SceneSwitcherNode pattern can properly change scenes so that update is
called on the first frame after the change.
> Add beforeUpdate node hook

- nin/dasBoot/NodeManager.js
A node that was going to be replaced did not get it's inputs linked
properly. This commit fixes this issue.
> Fix bug with insertOrReplace

- .editorconfig
- .gitattributes
Reason: The linter gave me a wall of text telling that the line endings were not as expected (LF) in frontend js files
> Enforce Unix-style endings even in a Windows environment

- nin/backend/compile.js
- nin/backend/compress.js
This is needed to make revision-invite-2018 compile properly, probably
because it references FRAME_FOR_BEAN inside on or more of its render
methods.
> Add back ghetto-patching of FRAME_FOR_BEAN et al.

- nin/dasBoot/NodeManager.js
We need to either fully traverse the graph on beforeUpdate, iterate over
all the nodes linearly or DFS prefix-traverse the graph for beforeUpdate
to work properly in some edge cases, I think. This commits adds full
traversal to beforeUpdate.
> Fully traverse the graph on beforeUpdate

- package.json
- yarn.lock
node-uuid is deprecated, so to get rid of a warning on every nin
install, this upgrades sockjs to the latest patch version which no
longer depends on this deprecated package.
> Upgrade sockjs to fix uuid warning

- package.json
- yarn.lock
Both chokidar and webpack depended on old versions of fsevents, which is used for file watching on macOS. That version of fsevents did not come with pre-build binaries for node 10 which resulted in install issues on my machine. These new versions of chokidar and webpack depend on the latest version of fsevents which has binaries for node 10 pre-built, without losing support for older node versions (even down to 4.x).
Luckily, upgrading from webpack 2.x to 4.x is trivial compared to upgrading from webpack 1.x to 2.x \o/
This depends on #480
> Upgrade chokidar and webpack for node 10 compat

- nin/dasBoot/bootstrap.js
After upgrading webpack, the generated code in dasboot.js changed for
the cases where we do:
```
const {functionA, functionB} = require('./module');
window.functionA = functionA;
window.functionB = functionB;
```
When the closure compiler sees this during compilation of the demo, it
derps and doesn't recognize that we might actually use the local
variable `functionA` inside bootstrap.js directly, and removes the
variable.
Updating the code in this file to read the function from the window
scope explicitly works as a hack to make compilation work again.
In the future, we may fix this properly by removing everything from
window scope and using modules fully.
> Fix beat bean initing

- nin/frontend/package.json
- nin/frontend/yarn.lock
- yarn.lock
The version we currently had installed is reported to have a known
security vulnerability by github, and in the process of upgrading it, I
discovered we don't actually use it at all.
Also, I've updated yarn recently, and it seems like they have a new
feature where they include an integrity hash for every installed package
now.
> Remove bootstrap

- nin/backend/blank-project/src/SceneSwitcherNode.js
This fixes a graph rendering delay issue.
> Use beforeUpdate instead of update by default in SceneSwitcherNode.

- .gitignore
Nin uses yarn, so the package-lock file from npm is not needed. This will stop it from being checked in at a later stage.
> Adds package-lock to gitignore

- nin/backend/serve.js
- nin/backend/socket.js
- nin/backend/watch.js
- nin/frontend/app/scripts/components/editor/Connection.js
- nin/frontend/app/scripts/components/editor/GraphEditor.jsx
- nin/frontend/app/scripts/components/editor/GraphEditorInputOutput.js
- nin/frontend/app/scripts/components/editor/GraphEditorNode.js
- nin/frontend/app/scripts/components/main.tsx
- nin/frontend/app/styles/common.less
Now graph edges can be added and removed in a crude first-step
implementation of an editable ui. The plan is to slowly iterate towards
a slick solution over multiple pull requests.
This pull requests disables live watch reloads on res/graph.json. The
idea is that it is loaded from the backend only once, and from then on
the frontend is responsible for editing it, sending graph change events
to the backend for persistance.
> Add first steps towards an ui-editable graph

- .travis.yml
https://docs.travis-ci.com/user/conditions-v1
Better than guessing!
Also, this moves tagging of the commit, because I could not figure out
how to use an environment variable as part of the tag in the npm
provider template. This might not work, so the next things to test is to
also add a provider block for GitHub releases that will also mark the
publish as a release in GitHub and set the tag at the same time.
> Use travis documented way of reading env variables

- .travis.yml
The method tried in #509 looks like it crashed. Here's trying wrapping the previous version of comparing two environment variables in `"` to ensure they are compared as strings.
> Try new method of comparing environment variables

- .travis.yml
I think I _finally_ understood the docs on this feature now:
> condition: deploy when a single bash condition evaluates to true. This
must be a string value, and is equivalent to if [[ <condition> ]]; then
<deploy>; fi. For example, $CC = gcc.
The docs were inconsistent on whether or not the whole thing was wrapped
in strings. I think now, that if it's all in quotes it will be executed
at runtime as a bash if statement. Otherwise, it is evaluated by travis
and the _result_ is put as the condition in bash. So for instance,
travis can evaluate something to "true" and then put the string "true"
in if [[ true ]]; then
Hopefulle this should do the trick, and for good measure I included a
guard to ensure this only runs on master, now that I might have
overridden the conditions for when deploy …
> Fix syntax error in .travis.yml

- .travis.yml
FINALLY! I think I've already said this, but _now_ I know why travis
deploy to npm didn't work. The `before_deploy` step is _not_ an
appropriate place to set up variables that are needed to check if we
want to deploy. It seems like the life cycle goes something like this:
- install
- script
- after_success
- check the condition blocks of any deploy stages
- for each deploy stage that we _now_ know that we're going to run, run
the before_deploy stage
- actually run deploy
- run after_deploy
Now all that's left to be seen after this is merged, is if travis can
manage to push this tag back to github or not.
> Move travis tagging to after_success

- .travis.yml
This should take care of pushing the tag that Travis created when publishing to npm, as well as marking it as a release on GitHub.
> Automatically create release on GitHub from travis

- nin/frontend/tsconfig.json
Resolves error:
ERROR in [at-loader] ./node_modules/@types/react/index.d.ts:377:23
TS2304: Cannot find name 'Set'.
> Fixing compilerer error in frontend
