nin/dasBoot/loop.js
The bpm and subdivisions are currently hardcoded, which is ok for now.
See https://github.com/ninjadev/tyve/pull/4, and also heatseeker for usage.
=> Add BEATBEAN music syncing

nin/dasBoot/lib/Projector.js
=> Add three.js projector

nin/frontend/app/scripts/services/camera.js
As long as they have a this.camera defined
=> Allow camera fly-around to be used on all layers

nin/dasBoot/CameraController.js
Now it will produce values according to its input and not just random
garbage
=> Fix camera roll

nin/backend/compress.js
=> Yolo-patch FRAME_FOR_BEAT and BEAT_FOR_FRAME

nin/frontend/app/styles/main.css
This should make scrolling both horizontally and vertically in the layers panel a lot better.
=> Fix scrolling issues in layers panel

nin/backend/generate/TemplateLayer.js, nin/backend/generate/generate.js, nin/backend/nin, nin/backend/utils.js
This contains generator for empty baseLayer
=> Add generator to nin, requires manifest in projects

nin/frontend/app/scripts/controllers/top.js
innerText doesn't work in firefox
=> Switch innerText to textcontent

nin/dasBoot/LayerManager.js, nin/dasBoot/Loader.js, nin/frontend/app/scripts/controllers/main.js
This is needed for the live reloading part of the loader.
=> Add support for multiple concurrent Loaders

nin/frontend/app/scripts/controllers/bottom.js
Editing length of layers after #133 did not work as expected
=> Account for xScale when editing layer timings

README.md, nin/frontend/app/index.html, nin/frontend/app/scripts/controllers/top.js, nin/frontend/app/scripts/directives/keybinding.js, nin/frontend/app/scripts/directives/selectOnClick.js, nin/frontend/app/styles/main.css, nin/frontend/app/views/top-panel.html
Now values are automatically updated in the UI all the time, instead of
having to click buttons to get the values for each frame. Twyk is at the
same time removed.
=> Remove twyk, rework camera panel UI

nin/frontend/app/index.html, nin/frontend/app/scripts/controllers/main.js, nin/frontend/app/scripts/directives/menubar.js, nin/frontend/app/styles/main.css, nin/frontend/app/views/main.html, nin/frontend/app/views/menubar.html
=> Add extensible menu bar

nin/frontend/app/scripts/controllers/main.js, nin/frontend/app/scripts/directives/keybinding.js, nin/frontend/app/scripts/services/render.js, nin/frontend/app/styles/main.css, nin/frontend/app/views/menubar.html
=> Menu populate

nin/frontend/app/scripts/controllers/top.js
The function doesn't exist
Fixes #144
=> Remove stopFlyAroundInterval call

nin/dasBoot/bootstrap.js
=> Wrap resize in lambda, prevent stupid arguments.

nin/backend/generate/TemplateShaderLayer.js, nin/backend/generate/generate.js, nin/backend/generate/templateShader/fragment.glsl, nin/backend/generate/templateShader/uniforms.json, nin/backend/generate/templateShader/vertex.glsl, nin/backend/nin, nin/backend/socket.js, nin/backend/utils.js, nin/frontend/app/scripts/controllers/main.js, nin/frontend/app/scripts/services/demo.js
We can now generate resources from the frontend.
One more step towards full-fledged IDE.
=> Add generate to menu

nin/backend/generate/generate.js, nin/backend/layers.js, nin/backend/socket.js, nin/backend/utils.js
Manages adding and updating of layers, and ensures only one write to
layers.json occurs at a time.
=> Add layer module to backend

nin/backend/generate/generate.js, nin/backend/nin, nin/backend/socket.js, nin/backend/utils.js
=> Use nin.json as base for project root in all commands

nin/frontend/app/index.html, nin/frontend/app/scripts/controllers/bottom.js, nin/frontend/app/scripts/directives/ngRightClick.js, nin/frontend/app/styles/main.css, nin/frontend/app/views/bottom-panel.html
=> Bottom panel UI redesign

nin/frontend/app/views/bottom-panel.html
=> Add tooltip (title attribute) on layer bars

nin/dasBoot/CameraController.js, nin/dasBoot/LayerManager.js
Camera that follows the path of the actual camera, looks the same way, shakes the same way.
Shown together with the path visualization.
I couldn't get rotation to work, if someone wants to look into that.
=> Visualize camera

nin/frontend/app/scripts/directives/waveform.js, nin/frontend/app/styles/main.css
This halves rendering time, improves stability and tweaks the visuals.
=> Improve waveform rendering

nin/dasBoot/music.js, nin/dasBoot/shims.js
Add support for web audio api in Safari
=> Webkit audio

nin/frontend/app/scripts/controllers/main.js
The menu displayed wrong information when it comes to the key bindings.
=> Fix message error in nin view

nin/backend/compile.js
This produces smaller compiled output.
=> Remove debug flag from closure compiler

nin/frontend/package.json
0.4.1 had an obscure bug when building the frontend of the project
=> Fix grunt minor version

README.md, nin/backend/package.json, nin/backend/render.js
Works on Windows \o/
Needs to be tested on OS X and Linux.
=> Use ffmpeg for rendering. Improve readability of render module.

nin/dasBoot/loop.js, nin/frontend/app/scripts/services/demo.js, nin/frontend/app/styles/common.less, nin/frontend/app/views/top-panel.html
=> Add error display in nin frontend

nin/backend/blank-project/nin.json
nin.json was blank in the current inited project.
It is no more!
=> Fill out nin.json with default data for blank project

nin/backend/serve.js, nin/dasBoot/loop.js, nin/frontend/app/scripts/controllers/main.js, nin/frontend/app/scripts/services/demo.js, nin/frontend/app/styles/common.less, nin/frontend/app/views/top-panel.html
Now handles errors in parsing WS as well, and improves the layout.
=> Improve error handling

nin/frontend/app/index.html, nin/frontend/app/scripts/controllers/main.js, nin/frontend/app/scripts/filters/errorExcerpt.js, nin/frontend/app/scripts/filters/stackFormat.js, nin/frontend/app/styles/common.less, nin/frontend/app/views/top-panel.html
=> Iterate upon error message styling

nin/frontend/app/scripts/controllers/bottom.js, nin/frontend/app/scripts/controllers/main.js, nin/frontend/app/scripts/directives/keybinding.js
One can now halve and double the loop length with the press of a button!
Remix your prods live infront of a live audience, watch them go wild!
=> Add DJ features to cue points.

nin/frontend/app/scripts/controllers/top.js
This was broken. Ain't no more!
=> Correctly cancel flyaround intveral

nin/frontend/app/scripts/controllers/bottom.js
Fixes https://github.com/ninjadev/nin/issues/228
=> Fix initial position of x scale slider

nin/frontend/app/views/top-panel.html
Fixes https://github.com/ninjadev/nin/issues/230
=> Fix input field update bug

nin/frontend/app/scripts/controllers/bottom.js, nin/frontend/app/views/bottom-panel.html
=> Show relative bean when inspecting layer

nin/dasBoot/PathController.js
Needed for latest version of phonograph layer
=> Add feature for moving camera around part of circle

nin/dasBoot/lib/00_three.js, nin/dasBoot/lib/01_EffectComposer.js, nin/dasBoot/lib/BloomPass.js, nin/dasBoot/lib/ClearPass.js, nin/dasBoot/lib/ConvolutionShader.js, nin/dasBoot/lib/CopyShader.js, nin/dasBoot/lib/ImprovedNoise.js, nin/dasBoot/lib/MTLLoader.js, nin/dasBoot/lib/MaskPass.js, nin/dasBoot/lib/OBJLoader.js, nin/dasBoot/lib/RenderPass.js, nin/dasBoot/lib/ShaderPass.js
=> Update three 79

nin/backend/blank-project/nin.json, nin/backend/compile.js, nin/backend/compress.js, nin/backend/projectSettings.js
=> Add metadata to compiled nin executables

README.md
Do we need consent from daeken to publish this?
Edit: I sent him an email
=> Update README.md (add daeken testimonial)

nin/backend/serve.js
=> Use projectPath when reading files from disk

nin/backend/generate/TemplateNode.js, nin/backend/generate/generate.js, nin/backend/graph.js, nin/backend/serve.js, nin/backend/socket.js, nin/backend/watch.js, nin/dasBoot/Node.js, nin/dasBoot/NodeManager.js, nin/frontend/app/scripts/controllers/main.js, nin/frontend/app/scripts/directives/graphEditor.js
=> New autopositioner

nin/frontend/app/scripts/directives/graphEditor.js
=> Add back inputs that disappeared in rebase

README.md
=> Add webpack dependency declaration to README

nin/frontend/app/styles/common.less
This also fixes an issue where the body had a small useless scrollbar.
This fixes #272.
=> Make music bar fill entire width

.gitignore, README.md, nin/backend/Makefile, nin/backend/package.json, nin/backend/serve.js, nin/frontend/package.json
nin is not published on npm. This prq adds the pieces to make that possible.
=> Publish nin on NPM

nin/frontend/app/scripts/controllers/bottom.js
It is no longer used, so it might as well be removed.
=> Remove old layer panel background

README.md, nin/backend/.eslintrc.js, nin/backend/compress.js, nin/backend/graph.js, nin/backend/init.js, nin/backend/package.json, nin/backend/projectSettings.js, nin/backend/render.js, nin/backend/serve.js, nin/backend/shadergen.js, nin/backend/socket.js, nin/backend/utils.js, nin/backend/watch.js, nin/backend/yarn.lock
=> Eslint backend

.travis.yml, nin/backend/.eslintignore, nin/backend/generate/generate.js
This is working now. Not the cleanest, prettiest config, but it should be working.
=> Add travis.yml

nin/backend/compile.js
=> Add some emoji to compile.js console output

nin/backend/nin, nin/backend/serve.js
=> Add portopts

.gitignore, nin/backend/blank-project/.eslintrc.json
This continues our standard of good project defaults.
=> Add .eslintrc to project

nin/frontend/app/scripts/directives/menubar.js
Turns out this is less confusing.
=> Swap j and k keyboard shortcuts

nin/frontend/Makefile
This is the same change we did for the linter.
=> Update webpack command in Makefile

nin/backend/blank-project/res/graph.json, nin/backend/init.js, nin/frontend/app/scripts/controllers/main.js, nin/frontend/app/scripts/directives/editor/Connection.js, nin/frontend/app/scripts/directives/editor/GraphEditor.js, nin/frontend/app/styles/common.less
=> Reverse graph

nin/frontend/app/scripts/directives/menubar.js, nin/frontend/app/scripts/services/demo.js
=> Add shortcut to toggle stats (FPS counter etc)

nin/frontend/app/scripts/directives/editor/GraphEditor.js
=> Reverse y ordering

nin/dasBoot/CameraController.js, nin/frontend/app/index.html, nin/frontend/app/scripts/directives/editor/FlyaroundController.js, nin/frontend/app/scripts/directives/editor/GraphEditorNode.js, nin/frontend/app/scripts/services/camera.js, nin/frontend/app/styles/common.less, nin/frontend/webpack.config.js
Flycontrols will be available for all nodes extending `NIN.THREENode`. There's a button on these nodes for toggling flycontrols on/off.
=> Node based flycontrols

nin/backend/projectSettings.js
=> Add newline to end of nin.json in init

nin/dasBoot/NodeManager.js, nin/frontend/app/scripts/controllers/main.js
Nonexisting constructors (due to race conditions) and errors in your
node's constructor are now two separate errors again, to everyones
delight!
=> Refactor nodeManager instantiation logic

nin/frontend/app/scripts/directives/editor/GraphEditor.js
Before (circled problem areas):
After:
=> Improve graph flow rendering algorithm

nin/backend/generate/generate.js
Small fixes to the generation of shaders.
=> Shaders generation fix

nin/frontend/app/scripts/directives/editor/Connection.js, nin/frontend/app/scripts/directives/editor/GraphEditor.js, nin/frontend/app/scripts/directives/editor/GraphEditorInputOutput.js, nin/frontend/app/scripts/directives/editor/GraphEditorNode.js
=> Illustrate node active state in graph editor

nin/backend/compile.js, nin/backend/compress.js, nin/dasBoot/bootstrap.js
I think we still need to do some verification work to make sure that the entire graph handles identially to when in the nin editor, but at least it now creates a valid compiled demo that correctly loads, plays, and puts graphics on the screen.
=> Repair compilation

nin/dasBoot/bootstrap.js
We need this for a demo. Merge merge merge!
=> Fix alpha stuff

nin/backend/serve.js
This should resolve our spurious issues with loading nin projects!
=> Fix sorting function for project files

nin/backend/compile.js, nin/backend/dasbootgen.js, nin/backend/serve.js
=> Use common dasboot generation for compile and run

nin/backend/serve.js
=> Don't use const for variable that's rebound

nin/backend/serve.js, nin/frontend/app/index.html, nin/frontend/app/scripts/components/waveform.js, nin/frontend/app/scripts/demo.js, nin/frontend/app/scripts/socket.js, nin/frontend/app/scripts/utils/render.js
All the frontend code is also now port agnostic which makes it easier to
run nin on different ports. Even several nin's at once should be possible now.
=> Refactor frontend to use one port only

nin/frontend/app/scripts/components/main.js, nin/frontend/app/scripts/components/menubar.js
This feature has been severely lacking from our lives.
=> Add truck-nin as separate command

nin/dasBoot/bootstrap.js, nin/dasBoot/lib/ImprovedNoise.js
ImprovedNoise was inaccessible before this change.
=> Properly export/import the ImprovedNoise function

nin/backend/generate/TemplateCanvasNode.js, nin/backend/generate/generate.js, nin/frontend/app/scripts/components/menubar.js
=> Add generator for canvas node

nin/backend/compile.js, nin/backend/nin
flag is needed to build our ~~revision 2017~~ solskogen demo
=> The shader optimizer can't handle one of our larger shaders, so this

nin/frontend/app/scripts/components/main.tsx, nin/frontend/tsconfig.json
Depends on https://github.com/ninjadev/nin/pull/440
=> Remove dead code

nin/frontend/app/scripts/components/menubar.js, nin/frontend/app/scripts/demo.js
This makes it much nicer to skip around in demos.
=> Make jog keyboard shortcuts quantized to the music

nin/frontend/app/scripts/components/demoplayer.js, nin/frontend/app/scripts/components/main.tsx, nin/frontend/app/scripts/demo.js, nin/frontend/app/scripts/utils/errorExcerptShader.js
Yay!
Depends on #453, let me rebase this once that lands.
=> Add error message display for shader

nin/frontend/app/scripts/components/editor/GraphEditor.jsx
=> Automatically center graph editor on graph change

nin/backend/projectSettings.js, nin/frontend/app/scripts/components/bottom.js, nin/frontend/app/scripts/components/waveform.js, nin/frontend/app/styles/common.less
They live in nin.json and are shown as clickable labels in the frontend.
Clicking them skips to the tagged point in time in the music.
=> Add labels

README.md
It's not all filled out yed, but it should make it easier to flesh
out the doc more in the time to come.
=> Add some sections in the readme that are usefull when starting out

nin/dasBoot/FullscreenRenderTargetPool.js, nin/dasBoot/RootNode.js, nin/dasBoot/ShaderNode.js, nin/dasBoot/THREENode.js, nin/dasBoot/bootstrap.js
This saves a bunch of resources and improves performance for demos with
many THREENodes.
=> Add render target pooling

nin/dasBoot/bootstrap.js
It wasn't supposed to be there, and didn't work.
=> Remove beforeUpdate exposal

nin/frontend/app/scripts/components/editor/GraphEditorInputOutput.js
Depends on https://github.com/ninjadev/nin/pull/449
=> Rewrite GraphEditorInputOutput to use jsx

nin/frontend/app/scripts/components/editor/GraphEditorNode.js
Depends on https://github.com/ninjadev/nin/pull/450
=> Rewrite GraphEditorNode to use jsx

.travis.yml
Last try also resulted in the condition being falsy. Do you think this will help?
=> Try to add quotes around environment variables

.travis.yml
Developing against travis is _horrible_!
=> Switch to TRAVIS_BUILD_DIR before deploying

README.md
And say a bit about how and when to use
=> Mention the existence of Random
